name: first-function
namespace: default
runtime: nodejs12
source:
    sourceType: git
    url: https://github.com/pPrecel/kyma-functions.git
    repository: first-function
    reference: master
    baseDir: "/git functions/nodejs12"
